scan_to_scan_filter_chain:
  ros__parameters:

    filter1:
      name: remove_wheelchair_body
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link

        min_x: -0.46
        max_x: 1.05

        min_y: -0.40
        max_y: 0.40

        min_z: -0.20
        max_z: 1.20

        invert: false
