cmake_minimum_required(VERSION 3.8)
project(swan_market)
find_package(ament_cmake REQUIRED)
install(DIRECTORY launch models config scripts DESTINATION share/${PROJECT_NAME} PATTERN "__pycache__" EXCLUDE)
if(BUILD_TESTING)
  find_package(ament_cmake_pytest REQUIRED)
  ament_add_pytest_test(world_selection test/test_world_selection.py)
endif()
ament_package()
